version: '3.1'
services:
    # redis:
    #     image: 'redis:alpine'

    mariadb:
        image: 'mariadb:latest'
        working_dir: /var/www
        volumes:
            - './src:/var/www'
        environment:
            - MYSQL_ROOT_PASSWORD=pwd
            - MYSQL_DATABASE=shreemad
        ports:
            - '3306:3306'
        networks:
            - backend

    adminer:
        image: adminer
        links:
            - mariadb
        ports:
            - 8005:8080
        networks:
            - backend

    webserver:
        image: 'nginx:alpine'
        container_name: nginx
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        links:
            - php-fpm
            - mariadb
        networks:
            - backend

    php-fpm:
        build: docker/php-fpm
        container_name: app
        working_dir: /var/www
        volumes:
            - './src:/var/www'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
        networks:
            - backend

networks:
  backend:
    driver: bridge
